#!/usr/bin/env perl
#
# Create a table of images, checksums, and manifest files from
# the mirror list ("mirrors"), and the version list ("versions").
#

my $mainsite = "https://nomadbsd.org/download";

open(my $fh, '<', 'mirrors')
	or die("Couldn't open mirror list: $!");
my @mirrors = <$fh>;
close($fh);

open($fh, '<', 'versions')
	or die("Couldn't open version list: $!");

foreach $image_version (<$fh>) {
	chomp($image_version);
	next if ($image_version =~ /^$/);
	foreach my $arch (('amd64', 'i386', 'mac')) {
		print(qq(<a name="${image_version}${arch}"></a>\n));
		if ($arch eq 'amd64') {
			$arch_str = '64-bit/x86-64/amd64';
		} elsif ($arch eq 'i386') {
			$arch_str = '32-bit/IA-32/i386';
		} else {
			$arch_str = 'Mac x86-64';
		}
		print(qq(<h4>NomadBSD $image_version ($arch_str)</h4>\n));
		print(qq(<table class="download-table" style="width:100%">\n));
		print(qq(\t<tr class="header-table-row">\n));
		print(qq(\t\t<th class="square-table-header"><span>Location</span></th>\n));
		print(qq(\t\t<th class="square-table-header"><span>Image</span></th>\n));
		print(qq(\t\t<th class="square-table-header" title="Checksum (lzma)"><span>lzma</span></th>\n));
		print(qq(\t\t<th class="square-table-header" title="Checksum (image)"><span>image</span></th>\n));
		print(qq(\t\t<th class="square-table-header"><span>Manifest</span></th>\n));
		print(qq(\t</tr>\n));

		foreach (@mirrors) {
			chomp;
			next if (/^#/);
			next if (!/^([^\t]+)\t+([^\t]+)/);
			$url	  = $2;
			$location = $1;
			my $image;

			$image = "nomadbsd-$image_version";
			$base_version = $image_version;
			$base_version =~ s/([0-9]+).*/\1/;
			if ($base_version < 130) {
				if ($arch eq 'i386' and $image_version * 10 >= 13) {
					$manifest_url = "$url/nomadbsd-$image_version.i386.manifest";
				} else {
					$manifest_url = "$url/nomadbsd-$image_version.manifest";
				}
			} else {
				$manifest_url = "$url/nomadbsd-$image_version.$arch.manifest";
			}
			if ($arch eq 'amd64' and $base_version < 130) {
				$lzma_chksum  = "$mainsite/$image.img.lzma.sha256";
				$image_chksum = "$mainsite/$image.img.sha256";
				$image .= ".img.lzma";
			} else {
				$lzma_chksum  = "$mainsite/$image.$arch.img.lzma.sha256";
				$image_chksum = "$mainsite/$image.$arch.img.sha256";
				$image .= ".$arch.img.lzma";
			}
			print(qq(\t<tr>\n));
			print(qq(\t\t<td>$location</td>\n));
			print(qq(\t\t<td><a href="$url/$image"><img title="$url/$image" style="margin-left: 18px; margin-right: auto" width="25" src="downloadicon.svg"></a></td>\n));
			print(qq(\t\t<td><a href="$lzma_chksum">SHA256</a></td>\n));
			print(qq(\t\t<td><a href="$image_chksum">SHA256</a></td>\n));
			print(qq(\t\t<td><a href="$manifest_url">MANIFEST</a></td>\n));
			print(qq(\t</tr>\n));
		}
		print(qq(</table>\n));
	}
}

