#!/bin/sh

get_rootdir() {
	d=$1
	while [ $d -gt 0 ]; do
		echo -n "../"; d=$(expr $d - 1);
	done
}

for i in `find . -name "*.in"`; do
	i=$(echo $i | sed -E 's/^\.\/(.*)/\1/')
	targets="$targets ${i%in}html"
	sources="$sources $i"
done

echo "TARGETS = $targets"
echo
echo "all: \${TARGETS}"
echo
for i in $(echo $sources); do
	depth=$(echo "$i" | sed 's/[^\/]//g' | wc -c)
	depth=$(expr $depth - 1)
	rd=$(get_rootdir $depth)
	echo ${i%in}html:$i
	if [ ! -z "$rd" ]; then
		printf "\t./build_page -r $rd ${i%in}html < $i > \$@";
	else
		printf "\t./build_page ${i%in}html < $i > \$@";
	fi
	echo
	echo
done
echo "clean:"
printf "\t-rm -f \${TARGETS}\n"
 
